name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop , main ]

jobs:
  build:
    name: Build, Test, Docker
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Resolve dependencies
        run: mvn dependency:go-offline

      - name: Build and test
        run: mvn clean verify

      - name: Build Docker image
        run: docker build -t ordersadapter-app .